In [34]:
import pandas as pd 
import numpy as np
import tensorflow as tf

In [54]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM,Dense
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
train_data=pd.read_csv("train.csv")

In [23]:
train_data.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [24]:
train_data.shape

(20800, 5)

In [25]:
train_data.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [26]:
df=train_data.dropna()

In [27]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [28]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [29]:
df.shape

(18285, 5)

In [30]:
x=df.drop("label",axis=1)
y=df["label"]

In [31]:
x.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [32]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [33]:
print(x.shape)
print(y.shape)

(18285, 4)
(18285,)


In [36]:
voc_size=5000

In [45]:
message=x.copy()

In [48]:
#this is because when we remove stop words then we
message.reset_index(inplace=True)

In [49]:
message.head()

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text  
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...  
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...  
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...  
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...  
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...

In [39]:
from nltk.stem import PorterStemmer
import re 

In [40]:
from nltk.corpus import stopwords

In [50]:
#this is for removing all stopwords from the title
ps=PorterStemmer()
corpus=[]
for i in range(0,len(message)):
    review=re.sub("[^a-zA-Z]"," ",message["title"][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if word not in stopwords.words("english")]
    review=" ".join(review)
    corpus.append(review)

In [52]:
len(corpus)

18285

In [53]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [55]:
one_hot_vector=[one_hot(word,5000) for word in corpus]

In [56]:
one_hot_vector

[[691, 2632, 1688, 2681, 3325, 1457, 1253, 3017, 2791, 2556],
 [3589, 1826, 1, 3874, 4868, 1095, 2301],
 [2911, 3344, 784, 1896],
 [4563, 4022, 4469, 1973, 141, 523],
 [4248, 4868, 4985, 656, 4085, 4680, 4868, 4672, 1061, 1629],
 [3175,
  4860,
  4405,
  2068,
  3830,
  4055,
  2784,
  4613,
  793,
  3670,
  4500,
  1160,
  836,
  4486,
  2301],
 [2296, 4193, 3741, 2939, 4062, 217, 437, 1235, 1363, 3930, 2942],
 [1031, 1907, 3794, 1244, 492, 1362, 4055, 3552, 1363, 3930, 2942],
 [2413, 2009, 2005, 100, 1609, 3869, 3881, 3761, 4055, 457],
 [898, 534, 4213, 2958, 349, 1983, 4812, 2209],
 [482, 4483, 1878, 57, 3281, 1608, 4314, 4646, 4870, 806, 1202],
 [1973, 4716, 3325, 3869, 4055, 492],
 [4109, 1292, 884, 3884, 823, 3155, 2683, 4162, 3343],
 [506, 639, 1645, 2577, 882, 3552, 1387, 1363, 3930, 2942],
 [1495, 198, 3591, 3924, 1784, 1363, 3930, 2942],
 [3143, 3821, 3649, 3347, 4928, 1277, 1240, 4988, 3788, 1756],
 [1108, 4773, 1826],
 [4991, 1583, 4099, 3702, 4055, 965, 2796, 2301],
 [4501

In [57]:
#for equalization in size 
sen_length=20
embedded_docs=pad_sequences(one_hot_vector,padding="pre",maxlen=sen_length)

In [58]:
embedded_docs

array([[   0,    0,    0, ..., 3017, 2791, 2556],
       [   0,    0,    0, ..., 4868, 1095, 2301],
       [   0,    0,    0, ..., 3344,  784, 1896],
       ...,
       [   0,    0,    0, ..., 1363, 3930, 2942],
       [   0,    0,    0, ..., 1869, 1475, 1334],
       [   0,    0,    0, ..., 2949, 3994, 3818]])

In [59]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  691,
       2632, 1688, 2681, 3325, 1457, 1253, 3017, 2791, 2556])

In [61]:
#creating the MOdel
embedding_vector_feature=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_feature,input_length=sen_length))
model.add(LSTM(100))
model.add(Dense(1,activation="sigmoid"))
model.compile(loss="binary_crossentropy",optimizer='adam',metrics=["accuracy"])

In [62]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [65]:
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [66]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,test_size=0.2,random_state=42)

In [67]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
229/229 [==============================] - 8s 25ms/step - loss: 0.3195 - accuracy: 0.8495 - val_loss: 0.1993 - val_accuracy: 0.9152
Epoch 2/10
229/229 [==============================] - 5s 22ms/step - loss: 0.1426 - accuracy: 0.9437 - val_loss: 0.2030 - val_accuracy: 0.9171
Epoch 3/10
229/229 [==============================] - 5s 21ms/step - loss: 0.0984 - accuracy: 0.9638 - val_loss: 0.2385 - val_accuracy: 0.9117
Epoch 4/10
229/229 [==============================] - 5s 21ms/step - loss: 0.0673 - accuracy: 0.9768 - val_loss: 0.2469 - val_accuracy: 0.9141
Epoch 5/10
229/229 [==============================] - 5s 21ms/step - loss: 0.0442 - accuracy: 0.9848 - val_loss: 0.3128 - val_accuracy: 0.9103
Epoch 6/10
229/229 [==============================] - 5s 21ms/step - loss: 0.0259 - accuracy: 0.9922 - val_loss: 0.3703 - val_accuracy: 0.9141
Epoch 7/10
229/229 [==============================] - 5s 21ms/step - loss: 0.0172 - accuracy: 0.9958 - val_loss: 0.4455 - val_accuracy: 0.9147

In [68]:
y_pred=model.predict(X_test)

115/115 [==============================] - 1s 5ms/step


In [86]:
#here we are converting the output as 0 and 1  
y_pred=np.where(y_pred>0.5,1,0)

In [87]:
from sklearn.metrics import accuracy_score

In [88]:
from sklearn.metrics import confusion_matrix

In [89]:
confusion_matrix(y_test,y_pred)

array([[1903,  179],
       [ 160, 1415]], dtype=int64)

In [90]:
accuracy_score(y_test,y_pred)

0.9073010664479081

In [91]:
from sklearn.metrics  import classification_report

In [85]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.91      0.92      2082
           1       0.89      0.90      0.89      1575

    accuracy                           0.91      3657
   macro avg       0.91      0.91      0.91      3657
weighted avg       0.91      0.91      0.91      3657

